// @ts-nocheck 
/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */
import { types } from "mobx-state-tree"

/**
 * Typescript enum
 */

export enum ProductSubCategory {
  BREAKFAST_BUNDLES="BREAKFAST_BUNDLES",
FAVA_BEANS="FAVA_BEANS",
HOT_BREAKFAST="HOT_BREAKFAST",
LOW_CARB_BARS="LOW_CARB_BARS",
MEAL_BUNDLES="MEAL_BUNDLES",
OAT_SLICES="OAT_SLICES",
PLANT_BASED_COOKIES="PLANT_BASED_COOKIES",
PLANT_BASED_SMOOTHIES="PLANT_BASED_SMOOTHIES",
PLUS="PLUS",
PROTEIN_BITES="PROTEIN_BITES",
PROTEIN_COOKIES="PROTEIN_COOKIES",
PROTEIN_MUFFLINS="PROTEIN_MUFFLINS",
PROTEIN_OATS="PROTEIN_OATS",
PROTEIN_SHAKES="PROTEIN_SHAKES",
PROTEIN_YOGHURT="PROTEIN_YOGHURT",
REGULAR_MEALS="REGULAR_MEALS",
SALADS="SALADS",
SNACK_BUNDLES="SNACK_BUNDLES",
SOUPS="SOUPS",
SOUP_BUNDLES="SOUP_BUNDLES",
WLP_BUNDLES="WLP_BUNDLES",
WLP_SNACKS="WLP_SNACKS"
}

/**
* ProductSubCategory
*/
export const ProductSubCategoryEnumType = types.enumeration("ProductSubCategory", [
        "BREAKFAST_BUNDLES",
  "FAVA_BEANS",
  "HOT_BREAKFAST",
  "LOW_CARB_BARS",
  "MEAL_BUNDLES",
  "OAT_SLICES",
  "PLANT_BASED_COOKIES",
  "PLANT_BASED_SMOOTHIES",
  "PLUS",
  "PROTEIN_BITES",
  "PROTEIN_COOKIES",
  "PROTEIN_MUFFLINS",
  "PROTEIN_OATS",
  "PROTEIN_SHAKES",
  "PROTEIN_YOGHURT",
  "REGULAR_MEALS",
  "SALADS",
  "SNACK_BUNDLES",
  "SOUPS",
  "SOUP_BUNDLES",
  "WLP_BUNDLES",
  "WLP_SNACKS",
      ])
