// @ts-nocheck 
/* This is a mst-gql generated file, don't modify it manually */
/* eslint-disable */
/* tslint:disable */
import { types } from "mobx-state-tree"

/**
 * Typescript enum
 */

export enum ProductModelOrderBy {
  _createdAt_ASC="_createdAt_ASC",
_createdAt_DESC="_createdAt_DESC",
_firstPublishedAt_ASC="_firstPublishedAt_ASC",
_firstPublishedAt_DESC="_firstPublishedAt_DESC",
_isValid_ASC="_isValid_ASC",
_isValid_DESC="_isValid_DESC",
_publicationScheduledAt_ASC="_publicationScheduledAt_ASC",
_publicationScheduledAt_DESC="_publicationScheduledAt_DESC",
_publishedAt_ASC="_publishedAt_ASC",
_publishedAt_DESC="_publishedAt_DESC",
_status_ASC="_status_ASC",
_status_DESC="_status_DESC",
_unpublishingScheduledAt_ASC="_unpublishingScheduledAt_ASC",
_unpublishingScheduledAt_DESC="_unpublishingScheduledAt_DESC",
_updatedAt_ASC="_updatedAt_ASC",
_updatedAt_DESC="_updatedAt_DESC",
createdAt_ASC="createdAt_ASC",
createdAt_DESC="createdAt_DESC",
discontinuedAt_ASC="discontinuedAt_ASC",
discontinuedAt_DESC="discontinuedAt_DESC",
displayName_ASC="displayName_ASC",
displayName_DESC="displayName_DESC",
grossPrice_ASC="grossPrice_ASC",
grossPrice_DESC="grossPrice_DESC",
id_ASC="id_ASC",
id_DESC="id_DESC",
liveAt_ASC="liveAt_ASC",
liveAt_DESC="liveAt_DESC",
netPrice_ASC="netPrice_ASC",
netPrice_DESC="netPrice_DESC",
newTagEndDate_ASC="newTagEndDate_ASC",
newTagEndDate_DESC="newTagEndDate_DESC",
newTagStartDate_ASC="newTagStartDate_ASC",
newTagStartDate_DESC="newTagStartDate_DESC",
productStatus_ASC="productStatus_ASC",
productStatus_DESC="productStatus_DESC",
promotionTotal_ASC="promotionTotal_ASC",
promotionTotal_DESC="promotionTotal_DESC",
sku_ASC="sku_ASC",
sku_DESC="sku_DESC",
updatedAt_ASC="updatedAt_ASC",
updatedAt_DESC="updatedAt_DESC"
}

/**
* ProductModelOrderBy
*/
export const ProductModelOrderByEnumType = types.enumeration("ProductModelOrderBy", [
        "_createdAt_ASC",
  "_createdAt_DESC",
  "_firstPublishedAt_ASC",
  "_firstPublishedAt_DESC",
  "_isValid_ASC",
  "_isValid_DESC",
  "_publicationScheduledAt_ASC",
  "_publicationScheduledAt_DESC",
  "_publishedAt_ASC",
  "_publishedAt_DESC",
  "_status_ASC",
  "_status_DESC",
  "_unpublishingScheduledAt_ASC",
  "_unpublishingScheduledAt_DESC",
  "_updatedAt_ASC",
  "_updatedAt_DESC",
  "createdAt_ASC",
  "createdAt_DESC",
  "discontinuedAt_ASC",
  "discontinuedAt_DESC",
  "displayName_ASC",
  "displayName_DESC",
  "grossPrice_ASC",
  "grossPrice_DESC",
  "id_ASC",
  "id_DESC",
  "liveAt_ASC",
  "liveAt_DESC",
  "netPrice_ASC",
  "netPrice_DESC",
  "newTagEndDate_ASC",
  "newTagEndDate_DESC",
  "newTagStartDate_ASC",
  "newTagStartDate_DESC",
  "productStatus_ASC",
  "productStatus_DESC",
  "promotionTotal_ASC",
  "promotionTotal_DESC",
  "sku_ASC",
  "sku_DESC",
  "updatedAt_ASC",
  "updatedAt_DESC",
      ])
